### ISSUE TITLE
JAXB classes generate emtpy wrapper elements

### ISSUE THREAD

**Issue by reckart** [antleb/omtd-registry-api#9]
try to avoid empty wrapper elements, since some of them may be optional but when used they contain an obligatory element 
e.g. `<outputResourceInfo>` requires the `<processingResourceType>`
`<otherArchives>`

@pennyl67 @courado

**Comment by courado** [comment]
This is not an issue since jaxb does not use getters and setters.

[Test class](https://github.com/openminted/omtd-registry-api/blob/develop/src/test/java/eu/openminted/registry/TestComponent.java) to demonstrate marshalling and unmarshalling.

Results : [here](https://builds.openminted.eu/job/omtd-registry-api/eu.openminted$omtd-registry-api/67/consoleFull) Search for "T E S T S"

**Comment by reckart** [comment]
I see. Thanks. I am opening a respective issue here https://github.com/openminted/omtd-share-annotations/issues/16 .
